<?php

namespace Efrei\DoorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessRepository extends EntityRepository
{
	public function findActiveByDoor(\Efrei\DoorBundle\Entity\Door $door) {
		return $this->createQueryBuilder('a')
							->where('a.active = 1')
							->andwhere('a.door = :doorid')
							->setParameter('doorid', $door->getId())
							->getQuery()
              				->getResult();
	}
	
	public function findInactiveByDoor(\Efrei\DoorBundle\Entity\Door $door) {
		return $this->createQueryBuilder('a')
							->where('a.active = 0')
							->andwhere('a.door = :doorid')
							->setParameter('doorid', $door->getId())
							->getQuery()
              				->getResult();
	}

	public function findActiveByCard(\Efrei\DoorBundle\Entity\Card $card) {
		return $this->createQueryBuilder('a')
							->where('a.active = 1')
							->andwhere('a.card = :cardid')
							->setParameter('cardid', $card->getId())
							->getQuery()
              				->getResult();
	}
	
	public function findInactiveByCard(\Efrei\DoorBundle\Entity\Card $card) {
		return $this->createQueryBuilder('a')
							->where('a.active = 0')
							->andwhere('a.card = :cardid')
							->setParameter('cardid', $card->getId())
							->getQuery()
              				->getResult();
	}
	
}
