<?php

namespace Efrei\DoorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends EntityRepository
{
	public function AccessDoor($door) {
		
	
		$qb = $this->createQueryBuilder('Card')
					->leftJoin('Card.accesses', 'Access')
					->where('Access.door = :door')
					->setParameter('door', (int)$door)
					->andwhere('Access.active = 1')
				
		; 
			
		$query = $qb->getQuery();
		
		
		return $query->getResult();
	}
}
