<?php

namespace Efrei\DoorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DoorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoorRepository extends EntityRepository
{
	public function AccessCard($card) {
		
		
		$qb = $this->createQueryBuilder('Door')
					->leftJoin('Door.accesses', 'Access')
					->where('Access.card = :card')
					->setParameter('card', $card)
					->andwhere('Access.active = 1')
		;
		
		
			
		$query = $qb->getQuery();
		
		return $query->getResult();
	}
	
	
	public function findBatiment() {
	
		$qb = $this->createQueryBuilder('Door')
			->select('Door.batiment')
			->distinct('batiment')
			->orderBy('Door.batiment', 'ASC')
		;
		
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
