home:
    pattern:  /home
    defaults: { _controller: "EfreiDoorBundle:Home:index" }

EfreiDoorBundle_card:
    resource: "@EfreiDoorBundle/Resources/config/routing/card.yml"
    prefix:   /card

EfreiDoorBundle_group:
    resource: "@EfreiDoorBundle/Resources/config/routing/cardgroup.yml"
    prefix:   /group

EfreiDoorBundle_door:
    resource: "@EfreiDoorBundle/Resources/config/routing/door.yml"
    prefix:   /door

EfreiDoorBundle_access:
    resource: "@EfreiDoorBundle/Resources/config/routing/access.yml"
    prefix:   /access
