access:
    pattern:  /
    defaults: { _controller: "EfreiDoorBundle:Access:index" }

access_show:
    pattern:  /{id}/show
    defaults: { _controller: "EfreiDoorBundle:Access:show" }

access_list:
    pattern:  /{door}/{card}/list
    defaults: { _controller: "EfreiDoorBundle:Access:list" }

access_new:
    pattern:  /new
    defaults: { _controller: "EfreiDoorBundle:Access:new" }

access_create:
    pattern:  /create
    defaults: { _controller: "EfreiDoorBundle:Access:create" }
    requirements: { _method: post }

access_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EfreiDoorBundle:Access:edit" }

access_update:
    pattern:  /{id}/update
    defaults: { _controller: "EfreiDoorBundle:Access:update" }
    requirements: { _method: post|put }

access_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EfreiDoorBundle:Access:delete" }
    requirements: { _method: post|delete }

access_remove:
    pattern:  /{id}/remove
    defaults: { _controller: "EfreiDoorBundle:Access:remove" }
    requirements: { _method: post|delete }

access_remove_all:
    pattern:  /{door}/{card}/remove/all
    defaults: { _controller: "EfreiDoorBundle:Access:removeAll" }
    requirements: { _method: post|delete|get }

access_delete_from:
    pattern:  /{id}/delete/{entity}
    defaults: { _controller: "EfreiDoorBundle:Access:deleteFrom" }
    requirements: { _method: get }

access_check:
    pattern: /check/{door}/{cardcode}/{facilitycode}
    defaults: { _controller: "EfreiDoorBundle:Access:check" }
    requirements: { _method: get }
